version: 2

jobs:
  Node8 tests:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: node --version > node_version
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn coverage

  Node10 tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: node --version > node_version
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn coverage
      - run: curl -s https://codecov.io/bash | bash

  Release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: node --version > node_version
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "node_version" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: |
          git config --global user.email deploy@travis-ci.org
          git config --global user.name Deployment Bot
          git remote set-url origin "https://github.com/nodkz/mongodb-memory-server.git" > /dev/null 2>&1
          git checkout master
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      - run: yarn release --yes

workflows:
  version: 2
  build:
    jobs:
      - Node8 tests
      - Node10 tests
      - Release:
          requires:
            - Node8 tests
            - Node10 tests
          filters:
            branches:
              only: master
